export const routes = {
  login: "/login",
  dashboard: "/dashboard",
  salons: "/salons",
  mySalon: "/my-salon",
  owners: "/owners",
  createOwner: "/create-owner",
  plans: "/plans",
  subscriptions: "/subscriptions",
  featureAccess: "/feature-access",
  branches: "/branches",
  serviceCategories: "/service-categories",
  services: "/services",
  customers: "/customers",
  staff: "/staff",
  appointments: "/appointments",
  queueTokens: "/queue-tokens",
  invoices: "/invoices",
  payments: "/payments",
  staffEarnings: "/staff-earnings",
  myEarnings: "/my-earnings",
  payroll: "/payroll",
} as const;
